ShopBridgeApp/Models/ItemMaster.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridgeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}

ShopBridgeApp/Models/ShopBridgeDBModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridgeApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopBridgeDBEntities : DbContext
    {
        public ShopBridgeDBEntities()
            : base("name=ShopBridgeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
    }
}

ShopBridgeApp/Models/ShopBridgeDBModel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\CHIRAG\source\repos\ShopBridge\ShopBridgeApp\Models\ShopBridgeDBModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

ShopBridgeApp/Models/ShopBridgeDBModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

ShopBridgeApp/Controllers/ItemMasterController.cs
using ShopBridgeApp.Models;
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShopBridgeApp.Controllers
{
    public class ItemMasterController : Controller
    {
        private ShopBridgeDBEntities db = new ShopBridgeDBEntities();

        // GET: ItemMaster
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Grid()
        {
            return View(db.ItemMasters.ToList());
        }

        // GET: ItemMaster/Details/5
        public ActionResult Details(int? id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemMaster itemMaster = db.ItemMasters.Find(id);
            if (itemMaster == null)
            {
                return HttpNotFound();
            }
            return View(itemMaster);
        }

        // GET: ItemMaster/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemMaster itemMaster, HttpPostedFileBase postedImage)
        {
            if (ModelState.IsValid)
            {
                string uploadpath = "~/Uploads/";
                string path = "";
                if (postedImage != null)
                {
                    path = uploadpath + itemMaster.ItemName.Replace(" ", "") + DateTime.UtcNow.ToString("ddmmyyyyhhmmss") + Path.GetExtension(postedImage.FileName);
                }

                if (itemMaster.ItemID == 0)
                {
                    itemMaster.CreatedDate = DateTime.UtcNow;
                }
                else
                {
                    itemMaster.ModifiedDate = DateTime.UtcNow;
                }

                //Image Path
                itemMaster.Image = path;

                db.ItemMasters.Add(itemMaster);
                int returnVal = db.SaveChanges();
                if (returnVal > 0)
                {
                    //Saving Image
                    if (path != "")
                    {
                        if (!Directory.Exists(Server.MapPath(uploadpath)))
                        {
                            Directory.CreateDirectory(Server.MapPath(uploadpath));
                        }

                        postedImage.SaveAs(Server.MapPath(path));
                    }
                }
                ModelState.Clear();
                return View();
            }

            return View(itemMaster);
        }

        // GET: ItemMaster/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemMaster itemMaster = db.ItemMasters.Find(id);
            if (itemMaster == null)
            {
                return HttpNotFound();
            }
            return View(itemMaster);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ItemMaster itemMaster)
        {
            if (ModelState.IsValid)
            {
                db.Entry(itemMaster).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(itemMaster);
        }

        // GET: ItemMaster/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemMaster itemMaster = db.ItemMasters.Find(id);
            if (itemMaster == null)
            {
                return HttpNotFound();
            }
            return View(itemMaster);
        }

        // POST: ItemMaster/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemMaster itemMaster = db.ItemMasters.Find(id);
            if (itemMaster != null)
            {
                db.ItemMasters.Remove(itemMaster);
                db.SaveChanges();
            }

            return RedirectToAction("Grid");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopBridgeApp/Views/ItemMaster/Create.cshtml
@model ShopBridgeApp.Models.ItemMaster

@{
    ViewBag.Title = "Create";
    Layout = null;
}

<div class="wrapper">
    <div id="new-cover-spin" class="cover-spin">
        <div class="spinner-border text-success" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    @using (Ajax.BeginForm("Create", "ItemMaster",
        new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "itemnewform",
            HttpMethod = "POST",
            LoadingElementId = "new-cover-spin",
            OnComplete="GridLoad",
            OnBegin="return Validate()"
        },
        new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-3">
                <div class="form-group">
                    @Html.Label("Name", htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.ItemName, new { @class = "form-control", @data_required="true", @data_maxlength="100" })
                    @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-2">
                <div class="form-group">
                    @Html.Label("Price", htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Price, new { @class = "form-control",@data_required = "true",@data_decimal="true", @data_maxlength = "15" })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    @Html.Label("Description", htmlAttributes: new { @class = "control-label" })
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "3", @data_required = "true", @data_maxlength = "250" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-2">
                <div class="form-group">
                    @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
                    <input type="file" name="postedImage" id="file" />
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-2">
                @if (Model != null && Model.Image != null)
                {
                    <img src="@Url.Content(Model.Image)" />
                }
            </div>
        </div>

        <div class="row">
            <div class="col-12" style="text-align:center;">
                <div class="form-group">
                    <input type="submit" value="SAVE" class="btn btn-success" />
                    <input type="button" value="CANCEL" class="btn btn-dark" />
                </div>
            </div>
        </div>
    }
</div>
<script>
    function Validate() {
        return FormValidate();
    }
</script>

ShopBridgeApp/Views/ItemMaster/Delete.cshtml
@model ShopBridgeApp.Models.ItemMaster

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ItemMaster</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShopBridgeApp/Views/ItemMaster/Details.cshtml
@model ShopBridgeApp.Models.ItemMaster

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="view view-detail">
    <div class="card" style="width: 18rem;">
        @if (!string.IsNullOrEmpty(Model.Image))
        {
            <img src="@Url.Content(Model.Image)" class="card-img-top" alt="...">
        }
        <div class="card-body">
            <h5 class="card-title">Name: @Model.ItemName</h5>
            <p class="card-text">Description: @Model.Description</p>
            @*<a href="#" class="btn btn-primary">Go somewhere</a>*@
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Price: $ @Model.Price</li>
        </ul>
    </div>
    <div class="m-2">
        <a href="@Url.Action("Index")"><i class="fa fa-arrow-left"></i> Back</a>
    </div>
</div>

ShopBridgeApp/Views/ItemMaster/Edit.cshtml
@model ShopBridgeApp.Models.ItemMaster

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ItemMaster</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemID)

        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShopBridgeApp/Views/ItemMaster/Grid.cshtml
@model IEnumerable<ShopBridgeApp.Models.ItemMaster>
@{
    Layout = null;
}
<div class="wrapper">
    <div id="grid-cover-spin" class="cover-spin">
        <div class="spinner-border text-success" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ItemName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th style="width:8%">
                        @Html.DisplayNameFor(model => model.Image)
                    </th>
                    <th style="width:10%"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ItemName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            @if (item.Image != null && item.Image != "")
                            {
                                <img src="@Url.Content(item.Image)" class="grid-img" />
                            }
                        </td>
                        <td>
                            <a class="btn btn-primary" title="View" href="@Url.Action("Details",new { id=item.ItemID})"><i class="fa fa-eye"></i></a>
                            <a class="btn btn-danger" title="View" onclick="deleteitem(@item.ItemID)"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    function deleteitem(id) {
        if (id != '' && confirm("Want to delete this item?")) {
            $.ajax({
                url: '/ItemMaster/Delete',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({ id: id }),
                success: function (data) {
                    GridLoad();
                },
                complete: function () {
                    $('#grid-cover-spin').hide();
                },
                beforeSend: function (xhr) {
                    $('#grid-cover-spin').show();
                }
            });
        }
    }
</script>

ShopBridgeApp/Views/ItemMaster/Index.cshtml
@{
    ViewBag.Title = "Item Master";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-12" id="itemnewform">
        @{Html.RenderAction("Create", "ItemMaster");}
    </div>
    <div class="col-12" id="itemgrid">
        @{Html.RenderAction("Grid", "ItemMaster");}
    </div>
</div>
<script>
    function GridLoad() {
        $.ajax({
            url: '/ItemMaster/Grid',
            type: 'GET',
            success: function (data) {

                $('#itemgrid').html();
                if (data != undefined) {
                    $('#itemgrid').html(data);
                }
            },
            complete: function () {
                $('#grid-cover-spin').hide();
            },
            beforeSend: function (xhr) {
                $('#grid-cover-spin').show();
            }
        });
    }
</script>

ShopBridgeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/font-awesome/css/font-awesome.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/custom-validations.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/Home">Shop Bridge</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" href="@Url.Action("Index","ItemMaster")">Item Master</a>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>

  
    @RenderSection("scripts", required: false)
</body>
</html>